# Mostrato quando un giocatore viene rilevato dall'anti cheat
alert-message: "&3[Solar] &f%player% &7> &b%check% &cx%vl% &7%verbose%"

# Mostrato al giocatore quando viene espulso a causa di TransactionOrder
transaction-order-kick-message: "&cAn error occurred in your connection."